### ISSUE TITLE
Problem with firefox_preferences in _config.properties

### ISSUE THREAD

**Issue by dkline-920** [qaprosoft/carina#1077]
**Describe the bug**
I have added this line in my _config.properties:
firefox_args=NULL
firefox_preferences=dom.postMessage.sharedArrayBuffer.withCOOP_COEP=true,browser.tabs.remote.useCrossOriginOpenerPolicy=true,browser.tabs.remote.useCrossOriginEmbedderPolicy=true

I also have 
platform=*
browser=firefox
browser_version=*
selenium_host=http://localhost:4444/wd/hub

I am running FF78.02 locally.  When I create a simple testcase to get a driver and then launch the "about:config" url and then a long pause, I thought that should be able to verify the preferences were set in the browser, but I don't see them.  If I look at the selenium log and check the profile directory created by the test, I can't verify there either.   Selenium console is showing an error related to sharedArrayBuffer and I believe the preference is not being set.

**Logs/Links**

------------- Driver capabilities -----------
================================================

[36m2020-07-23 15:50:29[0;39m [33morg.reflections.Reflections[0;39m [[35mmain[0;39m] [[34mINFO[0;39m]: Reflections took 194 ms to scan 2 urls, producing 138 keys and 802 values 
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.R' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.webdriver.Screenshot' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.resources.Resources' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.AbstractTestListener' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.factory.ICustomTypePageFactory' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.Configuration' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.report.ReportContext
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.report.ReportContext' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.utils.messager.ZafiraMessager
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.messager.ZafiraMessager' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.utils.FileManager
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.FileManager' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.utils.resources.L10N
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.resources.L10N' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.webdriver.device.Device
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.webdriver.device.Device' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.webdriver.IDriverPool
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.webdriver.IDriverPool' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.utils.android.recorder.utils.AdbExecutor
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.android.recorder.utils.AdbExecutor' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.utils.mobile.IMobileUtils
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.mobile.IMobileUtils' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.crypto.CryptoTool
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.crypto.CryptoTool' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.utils.resources.L10Nparser
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.resources.L10Nparser' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.hcl.nomad_qa.mobile.NomadSetupNoResetTestCase
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.listeners.TestNamingListener
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.TestNamingListener' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.dataprovider
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.dataprovider' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.webdriver.DriverHelper
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.webdriver.DriverHelper' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.listeners.CarinaListener
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.CarinaListener' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.utils.PlaceholderResolver
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.utils.PlaceholderResolver' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] loggerName: com.qaprosoft.carina.core.foundation.listeners.CarinaListener$ShutdownHook
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] Updaged logger level for 'com.qaprosoft.carina.core.foundation.listeners.CarinaListener$ShutdownHook' to DEBUG
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] Updated thread_count=1
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] Updated data_provider_thread_count=1
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] Class: jar:file:/Users/davidkline/.m2/repository/com/qaprosoft/carina-core/6.4.38/carina-core-6.4.38.jar!/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.class
2020-07-23 15:50:29 CarinaListener [main-1] [INFO] CARINA_CORE_VERSION: 6.4.38
2020-07-23 15:50:29 TestNamingListener [main-1] [DEBUG] TestNamingListener->beforeConfiguration
2020-07-23 15:50:29 TestNamingListener [main-1] [DEBUG] testName: SetupOnly - startUp
2020-07-23 15:50:29 CarinaListener [main-1] [DEBUG] CarinaListener->beforeConfiguration
2020-07-23 15:50:29 AbstractTestListener [main-1] [DEBUG] AbstractTestListener->beforeConfiguration
2020-07-23 15:50:29 CapabilitiesLoader [main-1] [INFO] Loading capabilities to global context from config.noReset.properties
2020-07-23 15:50:29 CapabilitiesLoader [main-1] [INFO] Custom capabilities properties loaded: config.noReset.properties
2020-07-23 15:50:29 CapabilitiesLoader [main-1] [INFO] Set custom property: capabilities.noReset; value: true
2020-07-23 15:50:29 NomadNoResetTestCase [main-1] [INFO] carinaTestRunId: f0c608f4-e787-4736-b5ed-ce80a6db4105
2020-07-23 15:50:29 IDriverPool [main-1] [DEBUG] Starting new driver as nothing was found in the pool
2020-07-23 15:50:29 IDriverPool [main-1] [DEBUG] initDriver start...
2020-07-23 15:50:29 DriverFactory [main-1] [DEBUG] DriverFactory start...
2020-07-23 15:50:29 Configuration [main-1] [DEBUG] Return default DESKTOP driver_type
2020-07-23 15:50:29 AbstractCapabilities [main-1] [DEBUG] Set capabilities value as boolean: true
2020-07-23 15:50:29 AbstractCapabilities [main-1] [DEBUG] FireFox profile will use '32402' port number.
2020-07-23 15:50:29 AbstractCapabilities [main-1] [WARN] If you want to enable auto-download for FF please specify 'auto_download_apps' param
2020-07-23 15:50:29 FirefoxCapabilities [main-1] [DEBUG] Firefox caps: Capabilities {acceptInsecureCerts: true, browserName: firefox, carinaTestRunId: f0c608f4-e787-4736-b5ed-ce8..., firefox_profile: org.openqa.selenium.firefox..., moz:firefoxOptions: {args: [], profile: UEsDBBQACAgIAE5+91AAAAAAAAA...}, name: default, noReset: true, takesScreenshot: false, version: }
Jul 23, 2020 3:50:32 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2020-07-23 15:50:33 DesktopFactory [main-1] [INFO] Browser window was maximized
2020-07-23 15:50:33 DriverFactory [main-1] [DEBUG] DriverFactory finish...

**Web (please complete the following information):**
 - firefox
 - 78.02
selenium-server-standalone-3.141.59.jar
geckodriver 0.26
Mac Catalina

**Additional context**

**Comment by dkline-920** [comment]
I went back and create a test that just gets a firefox driver via options and set the preferences in the options and with this when I go to the profile directory pointed at in the session info in the log and look in pref.js there, I see the preferences I was not successfully setting with firefox_preferences.

        FirefoxOptions options = new FirefoxOptions();
        options.setAcceptInsecureCerts(true);
        options.addPreference("javascript.options.shared_memory", true);
        options.addPreference("dom.postMessage.sharedArrayBuffer.withCOOP_COEP", true);
        options.addPreference("browser.tabs.remote.useCrossOriginOpenerPolicy", **true**);
        options.addPreference("browser.tabs.remote.useCrossOriginEmbedderPolicy", **true**);
        LOGGER.info("INITIAL driver");
        WebDriver driver = new FirefoxDriver(options);

1595619623212	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/qj/9zqmp_ms3dg2j1hjshprl8bm0000gn/T/rust_mozprofile1uDkn0"

grep tabs /var/folders/qj/9zqmp_ms3dg2j1hjshprl8bm0000gn/T/rust_mozprofile1uDkn0/prefs.js
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.tabs.disableBackgroundZombification", false);
user_pref("browser.tabs.remote.separatePrivilegedContentProcess", false);
user_pref("browser.tabs.remote.useCrossOriginEmbedderPolicy", **true**);
user_pref("browser.tabs.remote.useCrossOriginOpenerPolicy", **true**);

**Comment by vdelendik** [comment]
@dkline-920, issue should be fixed by: https://github.com/qaprosoft/carina/pull/1080/files
you can use version with hotfix: 6.4.875-SNAPSHOT

**Comment by dkline-920** [comment]
@vdelendik , I tried the new snapshot and also the build without the fix with the firefox preferences in chrome_experimental_options as that is what I see is fixed, but it didn't resolve my issue.  I still don't find my preferences set in the prefs.js of the profile pointed at for the session. So, while this fixes an obvious issue, it doesn't resolve the underlying problem.

**Comment by dkline-920** [comment]
I think the correct approach may be to use the profile.setPreference on the preferences in firefox_preferences.

**Comment by dkline-920** [comment]
borrowing code from AbstractCapabilities, I have things working for now with this:
	public WebDriver getConfiguredFireFoxDriver() {
	    WebDriver driver;
	    FirefoxProfile ffProf = new FirefoxCapabilities().getDefaultFirefoxProfile();
        for (String preference : Configuration.get(Parameter.FIREFOX_PREFERENCES).split(",")) {
            if (preference.isEmpty()) {
                continue;
            }
            preference = preference.trim();
            String name = preference.split("=")[0].trim();
            String value = preference.split("=")[1].trim();
            if ("true".equalsIgnoreCase(value) || "false".equalsIgnoreCase(value)) {
                ffProf.setPreference(name, Boolean.valueOf(value));
            } else {
                ffProf.setPreference(name, value);
            }
        }
        ffProf.setPreference("webdriver_accept_untrusted_certs", true);
        ffProf.setPreference("webdriver_assume_untrusted_issuer", true);
        LoggingPreferences logPrefs = new LoggingPreferences();
        logPrefs.enable(LogType.BROWSER, java.util.logging.Level.ALL);
        DesiredCapabilities desiredCaps = new DesiredCapabilities();
        desiredCaps.setCapability("acceptSslCerts", true);
        desiredCaps.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);
        desiredCaps.setCapability(FirefoxDriver.PROFILE, ffProf);      
	    return getDriver("default",desiredCaps);
	}

**Comment by okamara** [comment]
Verification is blocked by https://github.com/zebrunner/zebrunner/issues/2180

**Comment by vdelendik** [comment]
tested on mine own
